import numpy as np
import typer

from romgw.config.constants import COMMON_TIME, PROJECT_ROOT, MODE_VALUES
from romgw.maths.rb import reduced_basis, mgs, gram_matrix
# from romgw.typing.core import RealArray, BBHSpinType, ModeType, ComponentType, DatasetType
from romgw.config.types import (
    RealArray,
    BBHSpinType,
    ModeType,
    ComponentType,
    DatasetType
)
# from romgw.typing.utils import validate_literal
from romgw.config.validation import (
    validate_literal,
    validate_dependent_literal
)
from romgw.utils.filesystem import empty_directory
from romgw.waveform.dataset import ComponentWaveformDataset

DATASET: DatasetType = "train"
COMPONENT_TOLERANCE_DICT = {"amplitude": 1e-12, "phase": 1e-10}

HELP_BBH_SPIN = 'Spin configuration: "NS" = no-spin, "AS" = aligned-spin, "PS" = precessing-spin.'
HELP_DATASET = 'Dataset label: "train_xl" = xl training data, "train" = training data, "test" = testing data.'
HELP_MODE = 'Spin-weighted spherical harmonic label (l, m): "2,2", "2,1", "3,2", "3,3", "4,4", or "4,3".'
HELP_COMPONENT = 'Waveform component: "amplitude" or "phase".'
HELP_SAVING = "Whether to save redued basis and greedy errors."
HELP_VERBOSE = "Enable verbose output."

app = typer.Typer(help="Reduced Order Modelling of Gravitational Waves CLI")

@app.command()
def main(
    bbh_spin: BBHSpinType = typer.Option(..., help=HELP_BBH_SPIN),
    dataset: DatasetType = typer.Option(..., help=HELP_DATASET),
    mode: ModeType = typer.Option(..., help=HELP_MODE),
    component: ComponentType = typer.Option(..., help=HELP_COMPONENT),
    saving: bool = typer.Option(False, "--saving/--no-saving", help=HELP_SAVING),
    verbose: bool = typer.Option(False, "--verbose/--no-verbose", help=HELP_VERBOSE),
) -> None:
    """
    Find reduced basis for waveforms using a greedy algorithm.
    
    Employs a greedy algorithm to construct a reduced basis that optimally
    captures the morphological variation across waveforms generated by
    `generate_fiducial_waveforms.py`. The basis is built for a specific
    spin configuration, harmonic mode, and waveform component.
    
    Parameters
    ----------
    bbh_spin : BBHSpinType
        Spin configuration of the BBH. Can be "NS" (no-spin),
        "AS" (aligned-spin), or "PS" (precessing-spin).
    mode : ModeType
        Spin-weighted spherical harmonic mode label (e.g. "2,2", "3,3").
    component : ComponentType
        Waveform component (full modes are decomposed into their amplitude
        and phase parts). Can be "amplitude" or "phase".
    saving : bool, optional
        If True, saves the reduced basis and greedy errors returned by
        `reduced_basis` calls. Default is False.
    verbose : bool, optional
        If True, prints progress updates. Default is False.
    
    Returns
    -------
    None
    
    See Also
    --------
    reduced_basis : Greedy algorithm implementation for reduced basis
                    construction.

    Examples
    --------
    Find and save the reduced basis for the amplitude of the 2,2 mode of the
    GW produced by the merger of an NS BBH for the training set:

        $ python greedy_rb.py --bbh-spin NS --dataset train --mode 2,2 --component amplitude --saving
    """
    bbh_spin = validate_literal(
        value=bbh_spin,
        literal_type=BBHSpinType,
    )
    dataset = validate_literal(
        value=dataset,
        literal_type=DatasetType,
    )
    mode = validate_dependent_literal(
        value=mode,
        literal_type=ModeType,
        parent_value=bbh_spin,
        parent_literal_type=BBHSpinType,
        dependency_map=MODE_VALUES,
    )
    component = validate_literal(
        value=component,
        literal_type=ComponentType,
    )

    tolerance: float = COMPONENT_TOLERANCE_DICT[component]
    time: RealArray = COMMON_TIME
    data_dir = PROJECT_ROOT / "data" / bbh_spin / dataset / mode / component

    if verbose:
        typer.echo(f"Finding reduced basis for "
                   f"{bbh_spin=}, {mode=}, {component=}, {tolerance=}")
    
    raw_wf_dir = data_dir / "raw"
    waveforms = ComponentWaveformDataset.from_directory(raw_wf_dir,
                                                        n=(32768 if dataset=="train_xl" else None),  # my pc doesn't have enough ram to use the full 65536 waveforms
                                                        seed=(42 if dataset=="train_xl" else None),  # reproducibility
                                                        component=component)
    
    rb, errs = reduced_basis(waveforms,
                             tolerance=tolerance,
                             time=time,
                             verbose=verbose)

    rb = mgs(rb)  # for extra safe orthonormalisation

    if verbose:
        G = gram_matrix(rb, time)
        print(f"Gram matrix:")
        diag_mean = float(np.diagonal(G).mean())
        diag_min = float(np.diagonal(G).min())
        off_diag_mean = (float(np.sum(np.sum(G))) - (len(G) * diag_mean)) / (G.size - len(G))
        off_diag_max = float((G - G*np.identity(len(G))).max())
        print(f">>> diagonal mean: {diag_mean:.6e}\n"
              f">>> diagonal min : {diag_min:.6e}\n"
              f">>> off-diag mean: {off_diag_mean:.6e}\n"
              f">>> off_diag max : {off_diag_max:.6e}")

    if verbose:
        typer.echo("Greedy reduced basis element selection complete.")
    
    if saving:
        rb_dir = data_dir / "reduced_basis"

        rb_element_dir = rb_dir / "elements"
        rb_element_dir.mkdir(parents=True, exist_ok=True)
        empty_directory(rb_element_dir)
        rb.to_directory(rb_element_dir, overwrite=True)

        greedy_errors_file = rb_dir / "rb_greedy_errors.npy"
        np.save(file=greedy_errors_file, arr=errs, allow_pickle=False)

if __name__ == "__main__":
    app()
