import numpy as np
import typer

from romgw.config.env import COMMON_TIME, PROJECT_ROOT
from romgw.maths.rb import reduced_basis
from romgw.typing.core import RealArray, BBHSpinType, ModeType, ComponentType, DatasetType
from romgw.typing.utils import validate_literal
from romgw.utils.filesystem import empty_directory
from romgw.waveform.dataset import ComponentWaveformDataset

DATASET: DatasetType = "train"
COMPONENT_TOLERANCE_DICT = {"amplitude": 1e-12, "phase": 1e-10}

HELP_BBH_SPIN = 'Spin configuration: "NS" = no-spin, "AS" = aligned-spin, "PS" = precessing-spin.'
HELP_MODE = 'Spin-weighted spherical harmonic label (l, m): "2,2", "2,1", "3,2", "3,3", "4,4", or "4,3".'
HELP_COMPONENT = 'Waveform component: "amplitude" or "phase".'
HELP_SAVING = "Whether to save redued basis and greedy errors."
HELP_VERBOSE = "Enable verbose output."

app = typer.Typer(help="Reduced Order Modelling of Gravitational Waves CLI")

@app.command()
def main(
    bbh_spin: BBHSpinType = typer.Option(..., help=HELP_BBH_SPIN),
    mode: ModeType = typer.Option(..., help=HELP_MODE),
    component: ComponentType = typer.Option(..., help=HELP_COMPONENT),
    saving: bool = typer.Option(False, "--saving/--no-saving", help=HELP_SAVING),
    verbose: bool = typer.Option(False, "--verbose/--no-verbose", help=HELP_VERBOSE),
) -> None:
    """
    Find reduced basis for waveforms using a greedy algorithm.
    
    Employs a greedy algorithm to construct a reduced basis that optimally
    captures the morphological variation across waveforms generated by
    `generate_fiducial_waveforms.py`. The basis is built for a specific
    spin configuration, harmonic mode, and waveform component.
    
    Parameters
    ----------
    bbh_spin : BBHSpinType
        Spin configuration of the BBH. Can be "NS" (no-spin),
        "AS" (aligned-spin), or "PS" (precessing-spin).
    mode : ModeType
        Spin-weighted spherical harmonic mode label (e.g. "2,2", "3,3").
    component : ComponentType
        Waveform component (full modes are decomposed into their amplitude
        and phase parts). Can be "amplitude" or "phase".
    saving : bool, optional
        If True, saves the reduced basis and greedy errors returned by
        `reduced_basis` calls. Default is False.
    verbose : bool, optional
        If True, prints progress updates. Default is False.
    
    Returns
    -------
    None
    
    See Also
    --------
    reduced_basis : Greedy algorithm implementation for reduced basis
                    construction.

    Examples
    --------
    Find and save the reduced basis for the amplitude of the 2,2 mode of the
    GW produced by the merger of an NS BBH:

        $ python greedy_rb.py --bbh-spin NS --mode 2,2 --component amplitude --saving
    """
    bbh_spin = validate_literal(bbh_spin, BBHSpinType)
    mode = validate_literal(mode, ModeType)
    component = validate_literal(component, ComponentType)

    time: RealArray = COMMON_TIME

    if verbose:
        typer.echo(f"Finding reduced basis for "
                   f"{bbh_spin=}, {mode=}, {component=}")
    
    data_dir = PROJECT_ROOT / "data" / bbh_spin / "train" / mode / component
    
    raw_wf_dir = data_dir / "raw"
    waveforms = ComponentWaveformDataset.from_directory(raw_wf_dir,
                                                        component=component)
    
    rb, errs = reduced_basis(waveforms,
                             tolerance=COMPONENT_TOLERANCE_DICT[component],
                             time=time,
                             verbose=verbose)
    if verbose:
        typer.echo("Greedy reduced basis element selection complete.")
    
    if saving:
        rb_dir = data_dir / "reduced_basis"

        rb_element_dir = rb_dir / "elements"
        rb_element_dir.mkdir(parents=True, exist_ok=True)
        empty_directory(rb_element_dir)
        rb.to_directory(rb_element_dir, overwrite=True)

        greedy_errors_file = rb_dir / "rb_greedy_errors.npy"
        np.save(file=greedy_errors_file, arr=errs, allow_pickle=False)

if __name__ == "__main__":
    app()
