import numpy as np

from romgw.config.env import COMMON_TIME, PROJECT_ROOT
from romgw.maths.rb import reduced_basis
from romgw.typing.core import RealArray, BBHSpinType, ModeType, ComponentType
from romgw.typing.utils import validate_literal
from romgw.utils.filesystem import empty_directory
from romgw.waveform.dataset import ComponentWaveformDataset


DATASET = "train"
COMPONENT_TOLERANCE_DICT = {"amplitude": 1e-12, "phase": 1e-10}


def main(
    bbh_spin: BBHSpinType,
    mode: ModeType,
    component: ComponentType,
    time: RealArray = COMMON_TIME,
    saving: bool = False,
    verbose: bool = False,
) -> None:
    """
    Find a reduced basis for waveforms using a greedy algorithm.
    
    Employs a greedy algorithm to construct a reduced basis that optimally
    captures the morphological variation across waveforms generated by
    `generate_fiducial_waveforms.py`. The basis is built for a specific
    spin configuration, harmonic mode, and waveform component.
    
    Parameters
    ----------
    spin : {"NS", "AS", "P"}
        The complexity regarding the BBH spins. "NS" for no-spin, "AS" for
        aligned-spin, or "P" for precessing.
    mode : str
        The spin-weighted spherical harmonic mode label (e.g., "2,2", "3,3").
    component : {"amplitude", "phase"}
        The waveform component (full modes are decomposed into their amplitude
        and phase parts).
    
    Returns
    -------
    None
    
    See Also
    --------
    reduced_basis : Greedy algorithm implementation for reduced basis
                    construction.
    """
    # Validate literals. Raises exception if invalid.
    bbh_spin = validate_literal(bbh_spin, BBHSpinType)
    mode = validate_literal(mode, ModeType)
    component = validate_literal(component, ComponentType)

    print(f"Finding reduced basis ({bbh_spin=}, {mode=}, {component=}).")
    
    # Root directory for all IO operations in this script.
    data_dir = PROJECT_ROOT / "data" / bbh_spin / "train" / mode / component
    
    # Load waveforms.
    raw_wf_dir = data_dir / "raw"
    waveforms = ComponentWaveformDataset.from_directory(raw_wf_dir,
                                                        component=component)
    
    # Find reduced basis.
    rb, errs = reduced_basis(waveforms=waveforms,
                             tolerance=COMPONENT_TOLERANCE_DICT[component],
                             time=time,
                             verbose=verbose)
    print(f"{rb=}\n{errs=}")
    
    if saving:
        # Root directory for IO operations for reduced basis data.
        rb_dir = data_dir / "reduced_basis"

        # Save reduced basis elements.
        rb_element_dir = rb_dir / "elements"
        empty_directory(rb_element_dir)
        rb.to_directory(rb_element_dir, overwrite=True)

        # Save greedy errors.
        greedy_errors_file = rb_dir / "rb_greedy_errors.npy"
        np.save(file=greedy_errors_file, arr=errs, allow_pickle=False)


if __name__ == "__main__":
    main(bbh_spin="NS",
         mode="2,2",
         component="phase",
         saving=True,
         verbose=False)
